---
title: "Homework #4"
subtitle: "Exercises from Chapter 3.5: 2, 4, 5 and 10"
description: |
    **Assigned:** Friday, September 15th, 2023 <br>
    **Due:** Friday, September 29th, 2023
author: 
    -   name: Brynjólfur Gauti Guðrúnar Jónsson
        email: brynjolfur@hi.is
        url: https://www.hi.is/staff/brynjolfur
        affiliation: 
        -   name: School of Engineering and Natural Sciences, University of Iceland
            city: Reykjavík
            url: https://english.hi.is/school_of_engineering_and_natural_sciences
# Change this to pdf if you'd rather work in that format
format: html 
editor: source
title-block-banner: true
#### The setting below makes our HTML document self-contained so that we can turn it in ####
#### UNCOMMENT THE LONE BELOW SO THAT YOU CAN TURN IN YOUR HTML DOCUMENT ###################
# embed-resources: true 
---

{{< downloadthis index.qmd dname="hw4" label="Download the Quarto document used to render this file" type=primary class=downloadbutton >}}

# 2

Assume that $Y_i\vert\mu\overset{\mathrm{indep}}{\sim} \mathrm{Normal}(\mu,\sigma_i^2)$ for $i \in \{1, \dots, n\}$, with $\sigma_i$ known and improper prior distribution $\pi(\mu)=1$ for all $\mu$.

a. Give a formula for the MAP estimator for $\mu$

-----

**Solution:**

-----

b. We observe $n=3, Y_1=12, Y_2=10, Y_3=22, \sigma_2=\sigma_2=3$ and $\sigma_3=10$, compute the MAP estimate of $\mu$.

-----

**Solution:**

-----

c. Use numerical integration to compute the posterior mean of $\mu$.

-----

**Solution:**

-----

d. Plot the posterior distribution of $\mu$ and indicate the MAP and the posterior mean estimates on the plot.

-----

**Solution:**

-----

# 4

Consider the model 

$$
Y_i\vert\mu\overset{\mathrm{indep}}{\sim} \mathrm{Normal}(\mu,\sigma_i^2),
$$ 

for $i \in \{1, \dots, n\}$ where 

$$
\sigma_i^2\vert b \sim \mathrm{InvGamma}(a,b) \\ b\sim\mathrm{Gamma}(1,1)
$$

a. Derive the full conditional posterior distributions for $\sigma^2_2$ and $b$.

-----

**Solution:**

-----

b. Write pseudocode for Gibbs sampling, i.e. describe in detail each step of the Gibbs sampling algorithm.

-----

**Solution:**

-----

c. Write your own Gibbs sampling code (not in `JAGS`) and plot the marginal posterior density of each parameter. Assume $n=10$, $a=10$ and $Y_i=i$ for $i=1, \dots, 10$.

-----

**Solution:**

-----

d. Repeat the analysis with $a=1$ and comment on the convergence of the MCMC chain.

-----

**Solution:**

-----

# 5

Consider the model

$$
Y_i\vert\mu, \sigma^2 \sim \mathrm{Normal}(\mu,\sigma^2),\quad i=1,\dots,n,
$$

and

$$
Y_i\vert\mu,\delta, \sigma^2 \sim \mathrm{Normal}(\mu+\delta,\sigma^2),\quad i=n+1,\dots,n+m,
$$

where

$$
\mu,\delta\sim\mathrm{Normal}(0, 100^2) \\
\sigma^2\sim\mathrm{InvGamma}(0.01, 0.01).
$$

a. Give an example of a real experiment for which this would be an appropriate model.

-----

**Solution:**

-----

b. Derive the full conditional posterior distributions for $\mu$, $\delta$, and $\sigma^2$.

-----

**Solution:**

-----

c. Simulate a dataset from this model with $n=m=50$, $\mu=10$, $\delta=1$ and $\sigma=2$. Write your own Gibbs sampling code (not in `JAGS`) to fit the model above to the simulated data and plot the marginal posterior density for each parameter. Are you able to recover the true values reasonably well?

-----

**Solution:**

-----

d. Implement this model using `JAGS` and compare the results with the results in **.c**.

-----

**Solution:**

-----

# 10

As discussed in section 1.6, [24] report that the number of marine bivalve species discovered each year from 2010-2015 was 64, 13, 33, 18, 30 and 20. Denote $Y_t$ as the number of species discovered in year $2009+t$ (so that $Y_1=64$ is the count for 2010). Use `JAGS` to fit the model 

$$
Y_t\vert \alpha, \beta \overset{\mathrm{indep}}{\sim} \mathrm{Poisson}(\lambda_t)\\
\lambda_t = \exp(\alpha + \beta t) \text{ or equivalently } \log(\lambda_t) = \alpha + \beta t \\
\alpha,\beta \overset{\mathrm{indep}}{\sim} \mathrm{Normal}(0,10^2).
$$

Summarize the posterior of $\alpha$ and $\beta$ and verify that the MCMC sampler has converged. Does this analysis provide evidence that the rate of discovery is changing over time?




